# Generated by Django 3.2.5 on 2021-08-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Storyline',
        ),
        migrations.RenameField(
            model_name='storyline',
            old_name='code',
            new_name='content',
        ),
    ]
