# Generated by Django 3.2.5 on 2021-08-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210802_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyline',
            name='title',
        ),
        migrations.AddField(
            model_name='storyline',
            name='is_author',
            field=models.BooleanField(default=True),
        ),
    ]
