# Generated by Django 3.2.5 on 2021-09-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210909_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='name',
            field=models.CharField(default='Time Transmitter', max_length=200),
        ),
    ]
