# Generated by Django 3.2.5 on 2022-01-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_storylinetree_storyline'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyline',
            name='health',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storyline',
            name='hero_position_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storyline',
            name='hero_position_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storyline',
            name='story_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storyline',
            name='story_headline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storyline',
            name='wealth',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
