# Generated by Django 3.2.5 on 2022-01-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220124_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storyline',
            old_name='story_headline',
            new_name='papers_content',
        ),
        migrations.AddField(
            model_name='storyline',
            name='papers_headline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
